---
# tasks file for monitorix

- name: Verify Ansible meets our version requirements.
  assert:
    that: "ansible_version.full is version_compare('2.5', '>=')"
    msg: "You must update Ansible to at least 2.5 to use this role."

- include_tasks: monitorix.yml
