---
# tasks file for monitorix

- name: Verify Ansible meets Drupal VM's version requirements.
  assert:
    that: "ansible_version.full | version_compare('2.2', '>=')"
    msg: "You must update Ansible to at least 2.2 to use this role."

- include: monitorix.yml
