---
# tasks file for monitorix

- name: Verify Ansible meets our version requirements.
  assert:
    that: "ansible_version.full | version_compare('2.4', '>=')"
    msg: "You must update Ansible to at least 2.4 to use this role."

- include_tasks: monitorix.yml
