---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint --offline --exclude molecule
platforms:
  - name: monitorix-ubuntu-1604
    image: ubuntu:16.04
  - name: monitorix-ubuntu-1804
    image: ubuntu:18.04
  - name: monitorix-ubuntu-2004
    image: ubuntu:20.04
  - name: monitorix-debian-stretch
    image: debian:stretch
  - name: monitorix-debian-buster
    image: debian:buster
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
